import smtplib
import random

''' you have to provide gmail authorization to this python file tn access your gmail account otherwise it shows an error'''

server = smtplib.SMTP('smtp.gmail.com',587)
server.starttls()
server.login('sender password', 'enter the password generated by your gmail')
otp = ''.join([str(random.randint(0,9))for i in range(6)])
message = "hello your otp is"+ str(otp)
server.sendmail('sender password','reciver password', message)
server.quit()
abc = input("enter the otp send to your email:")
if otp ==abc:
    print("login successful")
else:
     print("invalid otp")